### ISSUE TITLE
Whats ur valorant settings (color, res etc...)

### ISSUE THREAD

**Issue by ntkernelsystem** [dgrfps/valorant#1]
I complied projects successfully!
But some problems...

- [ ] GUI bad output

- [ ] Not Working in The Range

![image](https://user-images.githubusercontent.com/68606364/180009608-a16f0472-47e6-4413-a994-a95c4af75c60.png)

**Comment by dgrfps** [comment]
What do you mean by gui bad output and in the range?

**Comment by ntkernelsystem** [comment]
![image](https://user-images.githubusercontent.com/68606364/180055506-9ff3c801-f2b4-4b3e-9521-e99ea2b406c2.png)
![image](https://user-images.githubusercontent.com/68606364/180055511-bc347a70-d3f2-420e-a0ec-fe1a2bddbc15.png)
![image](https://user-images.githubusercontent.com/68606364/180055522-89c503a8-fad9-43c1-930a-5419ad68285c.png)
![image](https://user-images.githubusercontent.com/68606364/180055551-8b9c13cf-20a2-409b-812e-f28f9df5dc5b.png)

**Comment by dgrfps** [comment]
MB i forgot to say, press XMBUTTON1, I pushed the update 5am and im very tired, please look at features/trigger.hpp to see the bind. Also rcs needs arruinou plugged and change the com port at mouse.hpp
