### ISSUE TITLE
arduino type and required

### ISSUE THREAD

**Issue by Artikus8** [dgrfps/valorant#2]
what arduino chip should it be exactly 
or does it work on all arduinos 
Do you need an extra host shield?

**Comment by dgrfps** [comment]
Hey, no extra shield required. It only work for few arduinos, i bought a pro micro, but for not to give bad information, its better to search beforebuying. 

According to this, any 32u4 based board.

https://www.arduino.cc/reference/en/language/functions/usb/mouse/

**Comment by dgrfps** [comment]
As arduino is open-source, you dont need to buy directly from their site, there's cheaper from others.

https://store-usa.arduino.cc/products/arduino-micro

**Comment by Artikus8** [comment]
Yes i see thanks for information dgrfps.I think we will need ATmega32u4 chip.Arduino uno in my hand is useless but i'll try.
