### ISSUE TITLE
COMPILATION

### ISSUE THREAD

**Issue by webchk** [dgrfps/valorant#3]
when I compile it keeps saying that it gave code 0

https://prnt.sc/gN7byYwA8384

**Comment by dgrfps** [comment]
Não estou mais trabalhando no projeto. No entanto verifique como na documentação do projeto se você desativou o sistema de hwid. 

Veja que codigo 0 significa que tudo está funcionando, e o programa foi encerrado propositalmente.

Uma vez que o HWID bloqueia usuarios não cadastrados, o programa fecha. Basta desativar está função no codigo, ou implementar seu provedor/API.

**Comment by dgrfps** [comment]
Por não obter resposta, vou marcar como resolvido. 
O código não apresenta erros de compilação nem execução.

**Comment by webchk** [comment]
mano eu não conseguir compilar, voce tem discord ?

**Comment by webchk** [comment]
ou algum contato rapido para eu tirar umas duvidas com voce, posso pagar pela consultoria

**Comment by dgrfps** [comment]
dgr#1835
Estarei disponível pelo período da noite.
