### ISSUE TITLE
can u help me compile it plz my discord is venxonli

### ISSUE THREAD

**Issue by VENXON** [dgrfps/valorant#6]
i cant compile it can u help me on discord stream or on anydesk

**Comment by dgrfps** [comment]
Are you having any problem? please relate your doubts 

Import the project on visual studio, the solution file is Void.sln (Import this/Open with Visualstudio).

Open project properties (Alt + Enter) and edit the libraries amd additional includes.

To compile press Control + B

**Comment by VENXON** [comment]
Hi  it always say cannot open input file glfw3.lib

**Comment by dgrfps** [comment]
You have to download GLFW binaries and import/update the import on project properties.
I used GLFW-3.3.8 for WIN64. 
You can download it's binaries on [GLFW.ORG](https://www.glfw.org/download.html).

I installed on `D:\libs\glfw-3.3.8.bin.WIN6\4`, as my Visual Studio is 2022, i include `lib-vc2022`.
Inside each `lib-vcxxxx` folder there is `glfw3.lib` and `glfw3.dll`.

**Comment by poroshok13** [comment]
Hello. I have a problem, LNK1104 cannot open the file "glfw3.lib". I installed glfw binaries, but I had a question regarding this, you wrote: "... and add the `/include` folder to the Include path.". I didn’t understand this moment either, can you explain it to me please?
