### ISSUE TITLE
Get in running

### ISSUE THREAD

**Issue by CarlosVP120** [dgrfps/valorant#7]
Hey! I managed to get it running, but how do I activate it?? I got the VOID window open and the game open but it is not shooting!

![image](https://github.com/dgrfps/valorant/assets/66846209/b2077ee7-6622-47b7-a5a6-53be4095a3ee)

**Comment by dgrfps** [comment]
On trigger page, Select a keybind  you need to hold it to keep the trigger running.
Select Fire Alias keybind, you've selected 'K', go to valorant settings and bind 'K' as a secondary key to shoot.

Something like: Primary key: Mouse 1, Secondary Key: K.

Also change enemy highlight color to your selected color.

**Comment by CarlosVP120** [comment]
Ohh do I need to have Valorant in Windowed Fullscreen??

**Comment by dgrfps** [comment]
As i wrote, https://github.com/dgrfps/valorant#info, try changing the saturation.
I do not have any video anymore, i used this project on Jul 17, 2022. 

Open the Range find a bot and try to change the settings while seeing the real time result.
