### ISSUE TITLE
CONFIG

### ISSUE THREAD

**Issue by poroshok13** [dgrfps/valorant#8]
I have a question about saturation. Im changing every 5 points, and check it, but its not fire in valorant. And do u have working config?
And what do the keybind and fire alias buttons mean?

**Comment by daguerpedro** [comment]
> And do u have working config?  

I have no config, i made it 2 years ago.
I'm not playing Valorant anymore.

>  what do the keybind and fire alias buttons mean?

I don't know if you didn't understand, or if it wasn't clear enough, but by 
> Select a 'Keybind' and alias it to Valorant as a seconday fire key.

in README [INFO section(https://github.com/dgrfps/valorant#info) I meant:
1) In the game goto settings, find something like Keyboard or Keybinds. 
2) Find the Fire/Shoot Option:
    - by default the primary key is the left mouse button
    - the secondary it's not assigned (Bind it to any key, like 'K' ).
3) Go back to the software click once in 'Fire Alias' and then hit the same key, in this case 'K'.
4) According to [Trigger source code](https://github.com/dgrfps/valorant/blob/3191b89e7e2b36781529d51e897a1580f4c76131/Valorant/new/features/Trigger.hpp#L24), Keybind is a key that has to be pressed while you want to use the triggerbot (Do not bind the same as Fire Alias).
